package com.mela.gui;

import com.mela.CoreCode.Pets;
import com.mela.CoreCode.User;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

public class DrLogIn extends javax.swing.JFrame {
    
    private DefaultTableModel model;

    /**
     * Creates new form DrLogIn
     */
    public DrLogIn(User user) {
        initComponents();
        addRowtoJTable();
        showName.setText(user.getName());
        displayNameLbl.setText("name");
        displayIDLbl.setText("dob");
        
    }
    
    public ArrayList<Pets> getListOfPets() {
        
        ArrayList<Pets> list = new ArrayList<>();
        
        Pets p1 = new Pets("Fluffy", "12.01.2019", "Maltese", "White", 1, "C:\\Users\\ilda\\Documents\\NetBeansProjects\\FinalProject\\src\\com\\mela\\gui\\minilogo.png");
        Pets p2 = new Pets("Tom", "03.01.2019", "Husky", "Brown", 2, "C:\\Users\\ilda\\Documents\\NetBeansProjects\\FinalProject\\src\\com\\mela\\gui\\minilogo.png");
        Pets p3 = new Pets("Mike", "12.02.2018", "Doberman", "Black", 3, "C:\\Users\\ilda\\Documents\\NetBeansProjects\\FinalProject\\src\\com\\mela\\gui\\minilogo.png");
        Pets p4 = new Pets("Bella", "07.11.2017", "Shih Tzu", "Brown", 4, "C:\\Users\\ilda\\Documents\\NetBeansProjects\\FinalProject\\src\\com\\mela\\gui\\minilogo.png");
        Pets p5 = new Pets("Coco", "2.05.2016", "Golden", "Gold", 5, "C:\\Users\\ilda\\Documents\\NetBeansProjects\\FinalProject\\src\\com\\mela\\gui\\minilogo.png");
        Pets p6 = new Pets("Mia", "8.01.2017", "Poodle", "Black", 6, "C:\\Users\\ilda\\Documents\\NetBeansProjects\\FinalProject\\src\\com\\mela\\gui\\minilogo.png");
        
        list.add(p1);
        list.add(p2);
        list.add(p3);
        list.add(p4);
        list.add(p5);
        list.add(p6);
        
        return list;
        
    }
    
    public void addRowtoJTable() {
        model = (DefaultTableModel) table.getModel();
        ArrayList<Pets> pd = getListOfPets();
        Object rowData[] = new Object[6];
        
        for (int i = 0; i < pd.size(); i++) {
            rowData[0] = pd.get(i).getName();
            rowData[1] = pd.get(i).getDOB();
            rowData[2] = pd.get(i).getBreed();
            rowData[3] = pd.get(i).getColor();
            rowData[4] = pd.get(i).getPetID();
            rowData[5] = new JButton("View");
            model.addRow(rowData);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        showName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        tryToAdoptBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        imgDisplayLbl = new javax.swing.JLabel();
        displayNameLbl = new javax.swing.JLabel();
        displayIDLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(0, 51, 204));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mela/gui/220px-User_icon_2.svg.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("You are signed in as Dr.");

        showName.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        showName.setForeground(new java.awt.Color(255, 255, 255));
        showName.setText("show data");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showName)
                            .addComponent(jLabel4))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(showName)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "DOB", "Breed", "Color", "PetID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
        }

        jScrollPane2.setViewportView(jScrollPane1);

        tryToAdoptBTN.setText("Try to adopt");
        tryToAdoptBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryToAdoptBTNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Available pets to adopt");

        imgDisplayLbl.setText("jLabel2");

        displayNameLbl.setText("jLabel5");

        displayIDLbl.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(displayNameLbl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(imgDisplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(tryToAdoptBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(displayIDLbl))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgDisplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(tryToAdoptBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(displayNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(displayIDLbl)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

//       to get the value of column of the selected row of the table ... int column = 0;
        int row = table.getSelectedRow();
        String name = table.getModel().getValueAt(row, 0).toString();
        String dob = table.getModel().getValueAt(row, 1).toString();
        String breed = table.getModel().getValueAt(row, 2).toString();
        String col = table.getModel().getValueAt(row, 2).toString();
        
        displayNameLbl.setText(name);
        displayIDLbl.setText(dob);
        Icon imgIcon = new ImageIcon(getListOfPets().get(row).getUri());        
        imgDisplayLbl.setIcon(imgIcon);
// TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void tryToAdoptBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryToAdoptBTNActionPerformed
        int row = table.getSelectedRow();
//        table.removeAll();
        getListOfPets().remove(getListOfPets().get(row));
        
        
//        table.repaint();
        // removing the adopted animal from the table
    }//GEN-LAST:event_tryToAdoptBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrLogIn(new User("Noizy", "Noizy", "Noizy", "Noizy", "Noizy")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel displayIDLbl;
    private javax.swing.JLabel displayNameLbl;
    private javax.swing.JLabel imgDisplayLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel1;
    private javax.swing.JLabel showName;
    private javax.swing.JTable table;
    private javax.swing.JButton tryToAdoptBTN;
    // End of variables declaration//GEN-END:variables
}
